import Head from 'next/head'
// import Image from 'next/image'
import Deck from "./../components/Deck";
// import styles from '/styles/Home.module.scss'

export default function Home() {
      return (
      <>
        <Head>
          <title>Card.js</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>


       <div className="App">
      <header className="App-header">
        <Deck title="Table" path="table" flipped = "2"/>
        <Deck title="Hand" path="hand" flipped = "2" />
      </header>
    </div>
      </>
    );
  }